title: "TechTinkering - Retro Computers, Programming, General Technical Tinkering"
description: > # this means to ignore newlines until "baseurl:"
  Retro Computers, Programming, General Technical Tinkering.
destination: ../gh-pages
lsi:         false
port: 4000
markdown: kramdown
permalink:   /:year/:month/:day/:title/
exclude: [design, scripts, README.md]

tag_title_prefix: "Articles Tagged With: "
